import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Toaster from "@/components/Toaster";
import { ThemeProvider } from "@/contexts/ThemeContext";

export const metadata = {
  title: "PromptVerse | AI Prompt Marketplace",
  description: "Generated by create next app",
};

const THEME_INIT_SCRIPT = `
  (function () {
    try {
      var saved = localStorage.getItem("theme");
      var theme = saved === "dark" || saved === "light" ? saved : "light";
      document.documentElement.setAttribute("data-theme", theme);
    } catch (e) {}
  })();
`;

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body className="min-h-full flex flex-col bg-[#EBF1F5] text-[#1E293B] dark:bg-[#151C24] dark:text-[#F1F5F9] transition-colors duration-300">
        <ThemeProvider>
          <Navbar />
          <main className="relative min-h-screen bg-[#EBF1F5] dark:bg-[#151C24] overflow-hidden">
            {children}
          </main>
          <Footer />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}