import { ToastContainer } from 'react-toastify';
import "@/app/globals.css"; // Ensure Tailwind v4 is imported here
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "PromptVerse | AI Prompt Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Navbar />
          <main className="relative min-h-screen bg-zinc-50 dark:bg-zinc-950 overflow-hidden">
            {children}
          </main>
          <Footer />
          <ToastContainer />
      </body>
    </html>
  );
}

